### ISSUE TITLE
AdvancedMarkerElement breaks after leaving the map page and returning to it

### ISSUE THREAD

**Issue by veljkocukic** [googlemaps/js-markerclusterer#691]
I am building a React app that implements clusters with AdvancedMarkerElement and when I load the page, everything works fine but when I leave the page that the map is placed on and go back to it markers disappear and I get weird console error.

```
const addMarkers = (map) => {
    const infoWindow = new google.maps.InfoWindow()
    const customMarker = document.createElement('div')
    customMarker.className = 'test'
    const markers = trees.map(([name, lat, lng, link]) => {
      const content = document.createElement('div')
      const imageContent = document.createElement('img')
      const text = document.createElement('p')
      text.innerText = 'John Smith'
      content.className = 'marker'
      imageContent.className = 'marker-image'
      imageContent.src = link
      content.appendChild(imageContent)
      content.appendChild(text)

      const marker = new google.maps.marker.AdvancedMarkerElement({    <---- This is where the console is pointing
        position: { lat: Number(lat), lng: Number(lng) },
        map,
        content,
      })

  
      return marker
    })

    new MarkerClusterer({
      markers,
      map,
      algorithm: new SuperClusterAlgorithm({ radius: 200 }),
    })
  }
```

This is what I get in console
```
Uncaught TypeError: Illegal constructor
    at new Lj (js?key=[keyThatIAmPassing]&language=en&region=GB&libraries=marker&v=beta&callback=mapsCallback:390:200)
    at new _.Mj (js?key=[keyThatIAmPassing]&language=en&region=GB&libraries=marker&v=beta&callback=mapsCallback:393:150)
    at new bI (js?key=[keyThatIAmPassing]&language=en&region=GB&libraries=marker&v=beta&callback=mapsCallback:136:280)
    at GlobalView.tsx:83:1
    at Array.map (<anonymous>)
    at addMarkers (GlobalView.tsx:71:1)
    at onLoad (GlobalView.tsx:40:1)
    at _.hi.<anonymous> (index.modern.mjs:122:1)
    at _.hi.<anonymous> (js?key=[keyThatIAmPassing]&language=en&region=GB&libraries=marker&v=beta&callback=mapsCallback:232:339)
    at _.K (js?key=[keyThatIAmPassing]&language=en&region=GB&libraries=marker&v=beta&callback=mapsCallback:233:93)
```

And this is how I display the map:

 ```
<GoogleMapsProvider
          googleMapsAPIKey={process.env.REACT_APP_GOOGLE_KEY}
          mapOptions={mapOptions}
          version='beta'
          libraries={['marker']}
          mapContainer={mapContainer}
          onLoadMap={onLoad}
        >
          <GlobalViewMapContainer ref={(node) => setMapContainer(node)} />
        </GoogleMapsProvider>
```

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react with :+1: so we can see what is popular when we triage.
--------

@veljkocukic Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._

**Comment by veljkocukic** [comment]
I managed to fix it by removing `libraries={['marker']}` and adding ```
const { AdvancedMarkerElement } = (await google.maps.importLibrary(
      'marker',
    )) as google.maps.MarkerLibrary
```

**Comment by veljkocukic** [comment]
I actually solved it for regular markers, AdvancedMarkerElements are still making the same problem
<img width="500" alt="Screenshot 2023-07-04 at 14 10 54" src="https://github.com/googlemaps/js-markerclusterer/assets/64806780/9456ae06-547f-4f15-8633-f5f882e5335b">

**Comment by shuhei-onuki** [comment]
I am also facing the exact same problem.

**Comment by veljkocukic** [comment]
> I am also facing the exact same problem.

I solved all of my problems with this by switching to another library and instead of using @ubilabs for the map wrapper, I used @googlemaps/react-wrapper and it works fine. So now I render a map like this:
 ```
<Wrapper apiKey={process.env.REACT_APP_GOOGLE_KEY} version='beta' libraries={['marker']}>
          <Map select={select} />
        </Wrapper>
```


This way, the map is created with ```
useEffect(() => {
    setMap(new google.maps.Map(ref.current, mapOptions))
  }, [])
```

**Comment by shuhei-onuki** [comment]
Thank you.
I will try.

**Comment by usefulthink** [comment]
This seems to be related to the way the maps-API is loaded (am I assuming correctly you've been using [@ubilabs/google-maps-react-hooks](https://www.npmjs.com/package/@ubilabs/google-maps-react-hooks)?) and has nothing to do with the markerclusterer.

The react-hooks library will try to reload the maps-api when parameters like api-key are changed (but also in case of hot-reloads). This was working fine in previous versions of the google maps API and allowed for changing api-parameters (like language and region) without reloading the page, but since the maps-API started to implement web-components this is no longer working and is causing these problems.
